name: Replicate Prod
description: 'Replicates the production instance on the given deployment'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'test'
  project-name:
    description: 'Project name'
    required: true
    default: 'digital'
  site-name:
    description: 'Site name'
    required: true
    default: 'test'
  openshift-server:
    description: 'OpenShift server'
    required: true
  dev-token:
    description: 'Dev token'
    required: true
  test-token:
    description: 'Test token'
    required: true
  prod-token:
    description: 'Prod token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Replicate Prod
      run: |
        chmod +x ./.github/actions/replicate_prod/replicate_prod.sh
        ./.github/actions/replicate_prod/replicate_prod.sh "${{ inputs.environment }}" "${{ inputs.project-name }}" "${{ inputs.site-name }}" "${{ inputs.openshift-server }}" "${{ inputs.dev-token }}" "${{ inputs.test-token }}" "${{ inputs.prod-token }}"
      shell: bash