name: Create Wordpress instance
description: 'Creates a new WordPress instance'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'test'
  site-name:
    description: 'Site name'
    required: true
    default: 'test'
  openshift-server:
    description: 'OpenShift server'
    required: true

runs:
  using: 'composite'
  steps:
    # - name: List files in current directory
    #   run: ls -al
    #   shell: bash
    - name: Create the instance
      run: |
        chmod +x ./.github/actions/create_wp_instance/deploy.sh
        ./.github/actions/create_wp_instance/deploy.sh "${{ inputs.environment }}" "${{ inputs.site-name }}" "${{ inputs.openshift-server }}" "${{ inputs.dev-token }}" "${{ inputs.test-token }}" "${{ inputs.prod-token }}"
      shell: bash
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_SITE_NAME: ${{ inputs.site-name }}
        INPUT_OPENSHIFT_SERVER: ${{ inputs.OPENSHIFT_SERVER }}
        INPUT_DEV_TOKEN: ${{ inputs.OPENSHIFT_DEV_API_TOKEN }}
        INPUT_TEST_TOKEN: ${{ inputs.OPENSHIFT_TEST_API_TOKEN }}
        INPUT_PROD_TOKEN: ${{ inputs.OPENSHIFT_PROD_API_TOKEN }}