name: Deploy Theme
description: 'Deploy BC Gov Block Theme'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'test'
  site-name:
    description: 'Site name'
    required: true
    default: 'test'
  openshift-server:
    description: 'OpenShift server'
    required: true
  dev-token:
    description: 'Dev token'
    required: true
  test-token:
    description: 'Test token'
    required: true
  prod-token:
    description: 'Prod token'
    required: true  
  keycloak-test-client-secret:
    description: 'Keycloak client secret'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, pdo_mysql
        coverage: none
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version
      shell: bash
    - name: Clone bcgov-wordpress-block-theme-digimod repository
      run: |
        git clone -b development https://github.com/bcgov/bcgov-wordpress-block-theme-digimod.git
      shell: bash
    - name: Deploy theme
      run: |
        chmod +x ./.github/actions/deploy_theme/deploy_theme.sh
        ./.github/actions/deploy_theme/deploy_theme.sh "${{ inputs.environment }}" "${{ inputs.site-name }}" "${{ inputs.openshift-server }}" "${{ inputs.dev-token }}" "${{ inputs.test-token }}" "${{ inputs.prod-token }}" "${{ inputs.keycloak-test-client-secret }}"
      shell: bash
