name: Deployplugins
description: 'Deployplugins'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'test'
  site-name:
    description: 'Site name'
    required: true
    default: 'test'
  openshift-server:
    description: 'OpenShift server'
    required: true
  dev-token:
    description: 'Dev token'
    required: true
  test-token:
    description: 'Test token'
    required: true
  prod-token:
    description: 'Prod token'
    required: true  
runs:
  using: 'composite'
  steps:

    - name: Deploy plugins
      run: |
        chmod +x ./.github/actions/deploy_plugins/deploy_plugins.sh
        ./.github/actions/deploy_plugins/deploy_plugins.sh "${{ inputs.environment }}" "${{ inputs.site-name }}" "${{ inputs.openshift-server }}" "${{ inputs.dev-token }}" "${{ inputs.test-token }}" "${{ inputs.prod-token }}"
      shell: bash
