name: Replicate Backup (Restore Backup)
description: 'Replicates a backup file from the backup instance on the given deployment'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'test'
  site-name:
    description: 'Site name'
    required: true
    default: 'test'
  openshift-server:
    description: 'OpenShift server'
    required: true
  dev-token:
    description: 'Dev token'
    required: true
  test-token:
    description: 'Test token'
    required: true
  prod-token:
    description: 'Prod token'
    required: true
  backup-number:
    description: 'Backup number'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Restore Backup
      run: |
        chmod +x ./.github/actions/restore_backup/restore_backup.sh
        ./.github/actions/restore_backup/restore_backup.sh "${{ inputs.environment }}" "${{ inputs.site-name }}" "${{ inputs.openshift-server }}" "${{ inputs.dev-token }}" "${{ inputs.test-token }}" "${{ inputs.prod-token }}" "${{ inputs.backup-number }}"
      shell: bash