name: Deploy Theme and plugins
description: 'Deploy BC Gov Block Theme and plugins'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'test'
  site-name:
    description: 'Site name'
    required: true
    default: 'test'
  openshift-server:
    description: 'OpenShift server'
    required: true
  dev-token:
    description: 'Dev token'
    required: true
  test-token:
    description: 'Test token'
    required: true
  prod-token:
    description: 'Prod token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, pdo_mysql
        coverage: none
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version
      shell: bash
    - name: Clone bcgov-wordpress-block-theme-digimod repository
      run: |
        git clone -b development https://github.com/bcgov/bcgov-wordpress-block-theme-digimod.git
      shell: bash
    - name: Deploy theme and plugins
      run: |
        chmod +x ./.github/actions/deploy_theme_and_plugins/deploy_theme_and_plugins.sh
        ./.github/actions/deploy_theme_and_plugins/deploy_theme_and_plugins.sh "${{ inputs.environment }}" "${{ inputs.site-name }}" "${{ inputs.openshift-server }}" "${{ inputs.dev-token }}" "${{ inputs.test-token }}" "${{ inputs.prod-token }}"
      shell: bash
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_SITE_NAME: ${{ inputs.site-name }}
        INPUT_OPENSHIFT_SERVER: ${{ inputs.OPENSHIFT_SERVER }}
        INPUT_DEV_TOKEN: ${{ inputs.OPENSHIFT_DEV_API_TOKEN }}
        INPUT_TEST_TOKEN: ${{ inputs.OPENSHIFT_TEST_API_TOKEN }}
        INPUT_PROD_TOKEN: ${{ inputs.OPENSHIFT_PROD_API_TOKEN }}