name: Deploy Theme and plugins
description: 'Deploy BC Gov Block Theme and plugins'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'test'
  site-name:
    description: 'Site name'
    required: true
    default: 'test'
  openshift-server:
    description: 'OpenShift server'
    required: true
  dev-token:
    description: 'Dev token'
    required: true
  test-token:
    description: 'Test token'
    required: true
  prod-token:
    description: 'Prod token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, pdo_mysql
        coverage: none
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version
      shell: bash
    - name: Clone bcgov-wordpress-block-theme-digimod repository
      run: |
        git clone -b development https://github.com/bcgov/bcgov-wordpress-block-theme-digimod.git
      shell: bash
    - name: Deploy theme and plugins
      run: |
        echo "Deploying to $INPUT_ENVIRONMENT"
        case "$INPUT_ENVIRONMENT" in
          "dev")
            token=$INPUT_DEV_TOKEN
            ;;
          "test")
            token=$INPUT_TEST_TOKEN
            ;;
          "prod")
            # token=$INPUT_PROD_TOKEN
            echo "For safety reasons, we won't run this action on prod!"
            exit 1
            ;;
          *)
            echo "Unknown environment: $INPUT_ENVIRONMENT"
            exit 1
            ;;
        esac
        oc login $INPUT_OPENSHIFT_SERVER --token=$token --insecure-skip-tls-verify=true
        
        # Deploy theme
        THEME_NAME="bcgov-wordpress-block-theme"
        NAMESPACE="c0cce6-$INPUT_ENVIRONMENT"
        OC_SITE_NAME=digital-$INPUT_SITE_NAME
        WORDPRESS_POD_NAME=$(oc get pods -n $NAMESPACE -l  app=wordpress,role=wordpress-core,site=${OC_SITE_NAME} -o jsonpath='{.items[0].metadata.name}')
        WORDPRESS_CONTAINER_NAME=$(oc get pods -n $NAMESPACE $WORDPRESS_POD_NAME -o jsonpath='{.spec.containers[0].name}')
        DATE=$(date +%Y-%m-%d-%H-%M)
        cd bcgov-wordpress-block-theme-digimod
        composer install
        # Check if the theme folder exists and rename it to create a backup
        # Download wp-cli in the GitHub Actions workspace
        # curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        # chmod +x wp-cli.phar
        # # Copy wp-cli to the WordPress instance and install wordpress
        # oc cp --no-preserve wp-cli.phar $NAMESPACE/$WORDPRESS_POD_NAME:/tmp/wp-cli.phar -c $WORDPRESS_CONTAINER_NAME
        # oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- chmod +x /tmp/wp-cli.phar 
        #oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- php /tmp/wp-cli.phar core install --url=${OC_SITE_NAME}.apps.silver.devops.gov.bc.ca --title="digital.gov.bc.ca Testing Framework" --admin_user=tester --admin_password=tester --admin_email=info@example.com

        tar -cf theme.tar --exclude=./github ./
        oc cp --no-preserve theme.tar $NAMESPACE/$WORDPRESS_POD_NAME:/var/www/html/wp-content/themes/theme.tar -c $WORDPRESS_CONTAINER_NAME
        oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- mv /var/www/html/wp-content/themes/$THEME_NAME /var/www/html/wp-content/themes/${THEME_NAME}_bak
        oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- mkdir /var/www/html/wp-content/themes/$THEME_NAME
        oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- tar -xmf /var/www/html/wp-content/themes/theme.tar -C /var/www/html/wp-content/themes/$THEME_NAME
        #oc cp --no-preserve . $NAMESPACE/$WORDPRESS_POD_NAME:/var/www/html/wp-content/themes/$THEME_NAME -c $WORDPRESS_CONTAINER_NAME
        oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- php /tmp/wp-cli.phar theme activate $THEME_NAME --allow-root

        # Deploy plugins
        NAMESPACE="c0cce6-$INPUT_ENVIRONMENT"
        OC_SITE_NAME=digital-$INPUT_SITE_NAME
        WORDPRESS_POD_NAME=$(oc get pods -n $NAMESPACE -l  app=wordpress,role=wordpress-core,site=${OC_SITE_NAME} -o jsonpath='{.items[0].metadata.name}')
        WORDPRESS_CONTAINER_NAME=$(oc get pods -n $NAMESPACE $WORDPRESS_POD_NAME -o jsonpath='{.spec.containers[0].name}')
        tar -cf plugins.tar --exclude=./.github --exclude=node_modules --exclude=./Archive --exclude=./bcgov-wordpress-block-theme-digimod ./*/
        oc cp --no-preserve plugins.tar $NAMESPACE/$WORDPRESS_POD_NAME:/var/www/html/wp-content/plugins/plugins.tar -c $WORDPRESS_CONTAINER_NAME
        oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- tar -xf /var/www/html/wp-content/plugins/plugins.tar -C /var/www/html/wp-content/plugins
        oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- php /tmp/wp-cli.phar plugin activate --all
        # for dir in `ls -d */`; do
        #   if [[ $dir != git* ]]; then
        #       oc cp --no-preserve . $NAMESPACE/$WORDPRESS_POD_NAME:/var/www/html/wp-content/plugins/$dir -c $WORDPRESS_CONTAINER_NAME
        #   fi
        # done 
      shell: bash
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_SITE_NAME: ${{ inputs.site-name }}
        INPUT_OPENSHIFT_SERVER: ${{ inputs.OPENSHIFT_SERVER }}
        INPUT_DEV_TOKEN: ${{ inputs.OPENSHIFT_DEV_API_TOKEN }}
        INPUT_TEST_TOKEN: ${{ inputs.OPENSHIFT_TEST_API_TOKEN }}
        INPUT_PROD_TOKEN: ${{ inputs.OPENSHIFT_PROD_API_TOKEN }}