# Manual+Scheduled workflow
# This is the scheduled workflow to create site backups daily.
name: Backup
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 2 * * *'
jobs:
  keepalive-job:  #From https://github.com/gautamkrishnar/keepalive-workflow, keep as seperate job for security.
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@2a8ae70f39b79fb50659d17ccc6f372f461813b2  #release 2.0.10. pin to this specific commit to prevent action code from being turned into bad actor later.

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Log in to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TEST_API_TOKEN }}      #--insecure-skip-tls-verify=true
      - name: Replicate Production
        uses: ./.github/actions/replicate_prod
        with:
          environment: prod
          site-name: backup
          openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
          dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
          test-token: ${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
          prod-token: ${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
      - name: Log in to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_PROD_API_TOKEN }}      #--insecure-skip-tls-verify=true
      # save the backup and delete one oldest backup
      - name: Update backup files
        run: |
          NAMESPACE="c0cce6-prod"
          OC_ENV=prod
          OC_SITE_NAME=digital-backup
          WORDPRESS_POD_NAME=$(oc get pods -n $NAMESPACE -l app=wordpress,role=wordpress-core,site=${OC_SITE_NAME} -o jsonpath='{.items[0].metadata.name}')
          WORDPRESS_CONTAINER_NAME=$(oc get pods -n $NAMESPACE $WORDPRESS_POD_NAME -o jsonpath='{.spec.containers[0].name}')

          cd .github/workflows
          oc cp backup.sh $NAMESPACE/$WORDPRESS_POD_NAME:/tmp/backup.sh -c $WORDPRESS_CONTAINER_NAME
          oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- chmod +x /tmp/backup.sh
          CMD1_RESULTS=$(oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- /bin/sh /tmp/backup.sh)
          echo "${CMD1_RESULTS}"

          #Generate GH Actions summary
          echo "### Created Backup" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line

          echo "### Command Results: " >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "${CMD1_RESULTS}" >> $GITHUB_STEP_SUMMARY