name: Deploy Plugin
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'test'
      site-name:
        description: 'Site name'
        required: true
        default: 'test'
      plugin:
        description: 'Plugin name'
        required: true
        default: ''
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy plugin
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          NAMESPACE="c0cce6-$ENVIRONMENT"
          OC_SITE_NAME=digital-${{ github.event.inputs.site-name }}
          echo "Deploying to $ENVIRONMENT"
          case "$ENVIRONMENT" in
              "dev")
              token=${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
              ;;
              "test")
              token=${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
              ;;
              "prod")
              token=${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
              OC_SITE_NAME=digital
              ;;
              *)
              echo "Unknown environment: $ENVIRONMENT"
              exit 1
              ;;
          esac
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=$token --insecure-skip-tls-verify=true
          plugin=${{ github.event.inputs.plugin }}

          if [ -d "$plugin" ]; then
            echo deploying $plugin

            WORDPRESS_POD_NAME=$(oc get pods -n $NAMESPACE -l  app=wordpress,role=wordpress-core,site=${OC_SITE_NAME} -o jsonpath='{.items[0].metadata.name}')
            WORDPRESS_CONTAINER_NAME=$(oc get pods -n $NAMESPACE $WORDPRESS_POD_NAME -o jsonpath='{.spec.containers[0].name}')

            cd $plugin
            tar -cf $plugin.tar --exclude=./.github --exclude=node_modules ./*
            oc cp --no-preserve $plugin.tar $NAMESPACE/$WORDPRESS_POD_NAME:/var/www/html/wp-content/plugins/$plugin.tar -c $WORDPRESS_CONTAINER_NAME
            oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- mkdir -p /var/www/html/wp-content/plugins/$plugin
            oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- tar -xf /var/www/html/wp-content/plugins/$plugin.tar -C /var/www/html/wp-content/plugins/$plugin
            oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- rm /var/www/html/wp-content/plugins/$plugin.tar
            echo $plugin deployed successfully.
          else  
            echo "plugin $plugin does not exist."
            exit 1
          fi
