name: Deploy Plugin
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'test'
      site-name:
        description: 'Site name'
        required: true
        default: 'test'
      plugin:
        description: 'Plugin name'
        required: true
        default: ''
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy plugin
        run: |
          ENVIRONMENT = ${{ github.event.inputs.environment }}
          echo "Deploying to $ENVIRONMENT"
          case "$ENVIRONMENT" in
              "dev")
              token=$DEV_TOKEN
              ;;
              "test")
              token=$TEST_TOKEN
              ;;
              "prod")
              # token=$PROD_TOKEN
              echo "For safety reasons, we won't run this action on prod!"
              exit 1
              ;;
              *)
              echo "Unknown environment: $ENVIRONMENT"
              exit 1
              ;;
          esac
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=$token --insecure-skip-tls-verify=true
          plugin = ${{ github.event.inputs.plugin }}
          if [ -d "$plugin" ]; then
            NAMESPACE="c0cce6-$ENVIRONMENT"
            OC_SITE_NAME=digital-${{ github.event.inputs.site-name }}
            WORDPRESS_POD_NAME=$(oc get pods -n $NAMESPACE -l  app=wordpress,role=wordpress-core,site=${OC_SITE_NAME} -o jsonpath='{.items[0].metadata.name}')
            WORDPRESS_CONTAINER_NAME=$(oc get pods -n $NAMESPACE $WORDPRESS_POD_NAME -o jsonpath='{.spec.containers[0].name}')

            cd $plugin
            if [ -f package.json ]; then

            tar -cf $plugin.tar --exclude=./.github --exclude=node_modules ./*/
            oc cp --no-preserve $plugin.tar $NAMESPACE/$WORDPRESS_POD_NAME:/var/www/html/wp-content/plugins/$plugin.tar -c $WORDPRESS_CONTAINER_NAME
            oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- tar -xf /var/www/html/wp-content/plugins/$plugin.tar -C /var/www/html/wp-content/plugins
          else  
            echo "plugin $plugin does not exist."
            exit 1
          fi
