name: e2e Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: npm -g i @wordpress/env
  #     - run: npm install --prefix multiple-blocks-plugin/
  #     - run: wp-env start --prefix multiple-blocks-plugin/
  #     - run: npm run test:e2e --prefix multiple-blocks-plugin/

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - name: Install dependencies
      uses: php-actions/phpunit@master
      with:
        bootstrap: vendor/autoload.php
        configuration: multiple-blocks-plugin/tests/phpunit.xml
        args: --coverage-text