name: Full Test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'test'
      site-name:
        description: 'Site name'
        required: true
        default: 'test'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      # - name: Log in to OpenShift
      #   run: |
      #     oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TEST_API_TOKEN }} --insecure-skip-tls-verify=true
      - name: Create a new Wordpress Instance
        uses: ./.github/actions/create_wp_instance
        with:
          environment: ${{ github.event.inputs.environment }}
          site-name: ${{ github.event.inputs.site-name }}
          openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
          dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
          test-token: ${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
          prod-token: ${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
      - name: Replicate Production
        uses: ./.github/actions/replicate_prod
        with:
          environment: ${{ github.event.inputs.environment }}
          site-name: ${{ github.event.inputs.site-name }}
          openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
          dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
          test-token: ${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
          prod-token: ${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
  take_screenshots:
    uses: ./.github/workflows/take_screenshots.yaml
    with:
      wordpressSiteUrl: test
  deploy_and_validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Sitemap Screenshots
        uses: ./.github/workflows/take_screenshots.yaml@main
        with:
          wordpressSiteUrl: test
      - name: Deploy theme
        uses: ./.github/actions/deploy_theme
        with:
          environment: ${{ github.event.inputs.environment }}
          site-name: ${{ github.event.inputs.site-name }}
          openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
          dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
          test-token: ${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
          prod-token: ${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
          keycloak-test-client-secret: ${{ secrets.KEYCLOAK_TEST_CLIENT_SECRET }}
      - name: Deploy plugins
        uses: ./.github/actions/deploy_plugins
        with:
          environment: ${{ github.event.inputs.environment }}
          site-name: ${{ github.event.inputs.site-name }}
          openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
          dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
          test-token: ${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
          prod-token: ${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
          keycloak-test-client-secret: ${{ secrets.KEYCLOAK_TEST_CLIENT_SECRET }}
      - name: Verify Screenshots
        uses: ./.github/actions/verify_screenshots
        continue-on-error: false
