name: Reconfigure SSO
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'test'
      site-name:
        description: 'Site name'
        required: true
        default: 'test'
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install OC CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        tar xvzf openshift-client-linux.tar.gz
        sudo mv oc kubectl /usr/local/bin/
    - name: Rename Miniorange plugin variables
      run: |
        ENVIRONMENT=${{ github.event.inputs.ENVIRONMENT }}
        SITE_NAME=${{ github.event.inputs.environment }}
        OC_SITE_NAME=digital-$SITE_NAME
        echo "Deploying to the site $OC_SITE_NAME in $ENVIRONMENT"
        case "$ENVIRONMENT" in
            "dev")
            token=${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
            ;;
            "test")
            token=${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
            ;;
            "prod")
            # token=${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
            echo "For safety reasons, we won't run this action on prod!"
            exit 1
            ;;
            *)
            echo "Unknown environment: $ENVIRONMENT"
            exit 1
            ;;
        esac
        oc login ${{ secrets.OPENSHIFT_SERVER }} --token=$token --insecure-skip-tls-verify=true
        NAMESPACE="c0cce6-$ENVIRONMENT"
        OC_ENV=$ENVIRONMENT
        OC_SITE_NAME=digital-${{ github.event.inputs.SITE-NAME }}
        WORDPRESS_POD_NAME=$(oc get pods -n $NAMESPACE -l app=wordpress,role=wordpress-core,site=${OC_SITE_NAME} -o jsonpath='{.items[0].metadata.name}')
        WORDPRESS_CONTAINER_NAME=$(oc get pods -n $NAMESPACE $WORDPRESS_POD_NAME -o jsonpath='{.spec.containers[0].name}')

        # Download wp-cli in the GitHub Actions workspace
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        # Copy wp-cli to the WordPress instance and install wordpress
        oc cp --no-preserve wp-cli.phar $NAMESPACE/$WORDPRESS_POD_NAME:/tmp/wp-cli.phar -c $WORDPRESS_CONTAINER_NAME
        oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- chmod +x /tmp/wp-cli.phar

        siteURL=https://${OC_SITE_NAME}.apps.silver.devops.gov.bc.ca
        ssoURI=''

        case $OC_ENV in
          'dev')
            ssoURI='https://test.loginproxy.gov.bc.ca/auth'
            clientSecret=${{ secrets.KEYCLOAK_TEST_CLIENT_SECRET}}
            ;;
          'test')
            ssoURI='https://test.loginproxy.gov.bc.ca/auth'
            clientSecret=${{ secrets.KEYCLOAK_TEST_CLIENT_SECRET}}
            ;;
          'prod')
            ssoURI=''
            clientSecret=${{ secrets.KEYCLOAK_PROD_CLIENT_SECRET}}
            ;;
          *)
            echo "No SSO integration set up for $SITE_NAME"
            exit 1
            ;;
        esac

        #run command to change miniorange plugin variables
        oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- bash -c "echo 'y' | php /tmp/wp-cli.phar digimod-config-mo $clientSecret $ssoURI $siteURL "
