name: Rename miniorange plugin contents
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'test'
      site-name:
        description: 'Site name'
        required: true
        default: 'test'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Rename Miniorange plugin variables
      run: |
        echo "Deploying to $ENVIRONMENT"
        case "$ENVIRONMENT" in
            "dev")
            token=${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
            ;;
            "test")
            token=${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
            ;;
            "prod")
            # token=${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
            echo "For safety reasons, we won't run this action on prod!"
            exit 1
            ;;
            *)
            echo "Unknown environment: $ENVIRONMENT"
            exit 1
            ;;
        esac
        oc login ${{ secrets.OPENSHIFT_SERVER }} --token=$token --insecure-skip-tls-verify=true
        NAMESPACE="c0cce6-${{ github.event.inputs.ENVIRONMENT }}"
        OC_ENV=${{ github.event.inputs.ENVIRONMENT }}
        OC_SITE_NAME=digital-${{ github.event.inputs.SITE-NAME }}
        WORDPRESS_POD_NAME=$(oc get pods -n $NAMESPACE -l app=wordpress,role=wordpress-core,site=${OC_SITE_NAME} -o jsonpath='{.items[0].metadata.name}')
        WORDPRESS_CONTAINER_NAME=$(oc get pods -n $NAMESPACE $WORDPRESS_POD_NAME -o jsonpath='{.spec.containers[0].name}')


        #run command to change miniorange plugin variables
        oc exec -n $NAMESPACE -c $WORDPRESS_CONTAINER_NAME $WORDPRESS_POD_NAME -- bash -c "echo 'y' | php /tmp/wp-cli.phar digimod-config-mo $KEYCLOAK_TEST_CLIENT_SECRET $SITE_NAME ${OC_SITE_NAME}.apps.silver.devops.gov.bc.ca"
