name: Restore Backup
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment ("prod" for prod)'
        required: true
        default: 'test'
      site-name:
        description: 'Site name ("digital" for prod)'
        required: true
        default: 'test'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      # - name: Log in to OpenShift
      #   run: |
      #     oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TEST_API_TOKEN }} --insecure-skip-tls-verify=true
      - name: Replicate Backup
        uses: ./.github/actions/replicate_prod
        with:
          environment: ${{ github.event.inputs.environment }}
          site-name: ${{ github.event.inputs.site-name }}
          openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
          dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
          test-token: ${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
          prod-token: ${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
