name: Restart instance
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'test'
      site-name:
        description: 'Site name'
        required: true
        default: 'test'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install OC CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        tar xvzf openshift-client-linux.tar.gz
        sudo mv oc kubectl /usr/local/bin/
    - name: Restart instance
      run: |
        ENVIRONMENT=${{ github.event.inputs.ENVIRONMENT }}
        SITE_NAME=${{ github.event.inputs.environment }}
        OC_SITE_NAME=digital-${{ github.event.inputs.site-name }}
        echo "Deploying to the site $OC_SITE_NAME in $ENVIRONMENT"
        case "$ENVIRONMENT" in
            "dev")
            token=${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
            ;;
            "test")
            token=${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
            ;;
            "prod")
            token=${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
            OC_SITE_NAME=digital
            ;;
            *)
            echo "Unknown environment: $ENVIRONMENT"
            exit 1
            ;;
        esac
        oc login ${{ secrets.OPENSHIFT_SERVER }} --token=$token --insecure-skip-tls-verify=true
        NAMESPACE="c0cce6-$ENVIRONMENT"
        OC_ENV=$ENVIRONMENT
        DEPLOYMENT=$(oc get deployment -n $NAMESPACE -l app=wordpress,site=$OC_SITE_NAME -o jsonpath='{.items[0].metadata.name}')

        #run command to change miniorange plugin variables
        oc rollout restart deployment/$DEPLOYMENT
