name: Restore Backup V2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment ("prod" for prod)'
        required: true
        default: 'test'
        type: choice
        options:
        - dev
        - test
        #will only allow running on -backup instance on prod.
        - prod
      project-name:
        description: 'Project'
        required: true
        type: choice
        options:
        - digital
      site-name:
        description: 'Site name ("backup" for prod)'
        required: true
        default: 'test'
      backup-number:
        description: 'Backup number (1 for latest, 2 for yesterday, etc..)'
        required: true
        default: '1'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Restore Backup V2
        uses: ./.github/actions/restore_backup_v2
        with:
          environment: ${{ github.event.inputs.environment }}
          project-name: ${{ github.event.inputs.project-name }}
          site-name: ${{ github.event.inputs.site-name }}
          openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
          dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
          test-token: ${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
          prod-token: ${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
          backup-number: ${{ github.event.inputs.backup-number }}
          s3-token: "${{ secrets.BCGOV_S3_SECRET_ACCESS_KEY }}"
          oc_nameplate: "f181a8"

      - name: Backup Restore Check V2
        uses: ./.github/actions/backup_restore_check_v2
        with:
          environment: ${{ github.event.inputs.environment }}
          project-name: ${{ github.event.inputs.project-name }}
          site-name: ${{ github.event.inputs.site-name }}
          openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
          dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
          test-token: ${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
          prod-token: ${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
          oc_nameplate: "f181a8"
