name: Restore Backup
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment ("prod" for prod)'
        required: true
        default: 'test'
      site-name:
        description: 'Site name ("digital" for prod)'
        required: true
        default: 'test'
      backup-number:
        description: 'Backup number (1 for latest, 2 for yesterday, etc..)'
        required: true
        default: '1'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Replicate Backup
        uses: ./.github/actions/restore_backup
        with:
          environment: ${{ github.event.inputs.environment }}
          site-name: ${{ github.event.inputs.site-name }}
          openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
          dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
          test-token: ${{ secrets.OPENSHIFT_TEST_API_TOKEN }}
          prod-token: ${{ secrets.OPENSHIFT_PROD_API_TOKEN }}
          backup-number: ${{ github.event.inputs.backup-number }}
