name: Take screenshots test
on:
  workflow_dispatch:
    inputs:
      site:
        description: 'Site name'
        required: true
        default: 'test'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Sitemap Screenshots
        uses: ./.github/actions/take_screenshots
        continue-on-error: false
        with:
          site: ${{ github.event.inputs.site }}