# Manual started workflow
name: Test Workflow
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/test