name: Verify screenshots
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - shell: bash
        # make sure directory for screenshots exists - we'll extract existing screenshots there that will be used for verification
        run: |
          mkdir -p /home/runner/work/wordpress-digimod/wordpress-digimod/testing/cypress/e2e/screenshots-for-https-digital-test-apps-silver-devops-gov-bc-ca
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: homepage-screenshot.yaml
           # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: /home/runner/work/wordpress-digimod/wordpress-digimod/testing/cypress/e2e/screenshots-for-https-digital-test-apps-silver-devops-gov-bc-ca
      - shell: bash
        # files get extracted into "cypress-screnshots" folder, move them out of it into parent directory and delete that folder
        run: |
          cd /home/runner/work/wordpress-digimod/wordpress-digimod/testing/cypress/e2e/screenshots-for-https-digital-test-apps-silver-devops-gov-bc-ca
          mv cypress-screenshots/* .
          rmdir cypress-screenshots
      - name: Sitemap Screenshots
        uses: cypress-io/github-action@v5
        id: screenshots
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: true
        with:
        # No recording of results in the cloud
          record: false
        # We need to force the install due to version checking  
          install-command: npm ci -f
          working-directory: testing
          browser: firefox
          spec: cypress/e2e/screenshot-tests.cy.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots-failed
          path: /home/runner/work/wordpress-digimod/wordpress-digimod/testing/cypress/e2e/screenshots-for-https-digital-test-apps-silver-devops-gov-bc-ca
          if-no-files-found: error # 'warn' or 'error' are also available, defaults to `warn`, also `ignore`
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-failed