name: Verify screenshots test
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sitemap Screenshots
        uses: ./.github/actions/verify_screenshots
        continue-on-error: false